collections:
    - name: ansible.netcommon
      version: ">=2.0.0"
    - name: f5networks.f5_modules
      source: https://github.com/F5Networks/f5-ansible.git#ansible_collections/f5networks/f5_modules
      type: git
      version: devel
