---
- name: Get BIG-IP Data Group List
  hosts: bigip-ve.hk.ntnxlab.local
  connection: local
  gather_facts: false

  tasks:
    - name: Setup provider
      ansible.builtin.set_fact:
        provider:
          server: "{{ ansible_host }}"
          # user: "{{ f5_admin_user }}"
          # password: "{{ f5_admin_password }}"
          server_port: "{{ f5_admin_port }}"
          validate_certs: false
          
    - name: Get Data Group List
      f5networks.f5_modules.bigip_command:
        provider: "{{ provider }}"
        commands:
          - list ltm data-group internal {{ f5_data_group_list }}
      register: result

    - debug:
        var: result.stdout
        
    - name: Find Active Machine
      f5networks.f5_modules.bigip_command:
        provider: "{{ provider }}"
        match: "any"
        warn: no
        commands:
          - bash -c "cat /var/prompt/ps1"
      register: result

    - name: Update data grou list records
      bigip_data_group:
        name: {{ f5_data_group_list }}
        internal: true
        records:
          - key: 172.16.66.129/32
            value: "rhel10.hk.ntnxlab.local"
      provider: "{{ provider }}"
      delegate_to: localhost

      - name: SAVE RUNNING CONFIG ON BIG-IP
      f5networks.f5_modules.bigip_config:
        provider: "{{ provider }}"
        save: true
      when: '"Active" in result.stdout'


