---
- name: BIG-IP SETUP
  hosts: bigip-ve.hk.ntnxlab.local
  connection: httpapi
  gather_facts: false

# Connection Info
  vars:
    provider:
      user: admin
      password: "NTNX4ever/"
      server: "{{ ansible_host }}"
      server_port: "{{ f5_admin_port }}"
      validate_certs: false
    ansible_user: "{{ provider.user }}"
    ansible_httpapi_password: "{{ provider.password }}"
    ansible_httpapi_port: "{{ provider.server_port }}"
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:
    - name: Install PKCS12 cert and key
      f5networks.f5_bigip.bigip_ssl_pkcs12:
        name: "app-demo"
        source: "/awx/certs/app-demo.p12"
        cert_pass: "password"
        state: present
            
    - name: Create a client SSL profile with a cert/key/chain setting
      f5networks.f5_modules.bigip_command:
        provider: "{{ provider }}"
        commands:
          - create ltm profile client-ssl {{ vip_name }}_new_ClientSSL_profile defaults-from hkt-clientssl-template sni-default true retain-certificate false cert-key-chain add { my_profile_certkey { cert app-demo key app-demo } }
      register: result
      delegate_to: localhost

    - debug:
        var: result.stdout
            
    - name: UPDATE A VIRTUAL SERVER
      f5networks.f5_modules.bigip_virtual_server:
        provider: "{{provider}}"
        name: "{{ vip_name }}"
        port: "443"
        profiles:
        - name: "{{ vip_name }}_ClientSSL_profile"
          context: client-side
        - name: "clientssl"
          context: client-side
        - oneconnect
        - http
      delegate_to: localhost
